---
hadoop:
  children:
    hadoop_masters:
    hadoop_slaves:
  vars:
    hadoop_version: 2.7.7
    hadoop_dir_name: "hadoop-{{ hadoop_version }}"
    hadoop_tarball_name: "{{ hadoop_dir_name }}.tar.gz"
    hadoop_tarball_url: "http://main:8080/{{ hadoop_tarball_name }}"
    hadoop_dir_dest: /opt
    hadoop_path: "{{ hadoop_dir_dest }}/hadoop"
    hadoop_master: "{{ groups['hadoop_masters'] | first }}"
    hadoop_user: "{{ ansible_user }}"
    hadoop_group: "{{ ansible_user }}"
    hadoop_slaves: "{{ groups['hadoop_slaves'] }}"
    hadoop_jdk_path: /opt/jdk
    hadoop_first_run: true

hadoop_masters:
  vars:
    hadoop_put_file_name: sample-graph
    hadoop_put_file_url: "http://main:8080/{{ hadoop_put_file_name }}"
    hadoop_put_hdfs_dest_dir: /subgraph-isomorphism/input
    hadoop_put_local_dest_dir: /opt
    hadoop_put_hadoop_path: "{{ hadoop_path }}"
